services:
    gonductor:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: "gonductor"
        ports:
            - 0.0.0.0:8080:8080
        networks:
            - gonductor_net
        restart: always
        volumes:
            - ./../:/go/src/app/
        logging:
          driver: json-file
          options:
              max-size: "5m"
              max-file: "2"
networks:
    gonductor_net:
